In [51]:
pip install kagglehub[pandas-datasets]

Requirement already satisfied: kagglehub[pandas-datasets] in /usr/local/lib/python3.12/dist-packages (1.0.2)
Requirement already satisfied: kagglesdk<1.0,>=0.1.22 in /usr/local/lib/python3.12/dist-packages (from kagglehub[pandas-datasets]) (0.1.23)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from kagglehub[pandas-datasets]) (26.2)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from kagglehub[pandas-datasets]) (6.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kagglehub[pandas-datasets]) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from kagglehub[pandas-datasets]) (4.67.3)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from kagglehub[pandas-datasets]) (2.2.2)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from kagglesdk<1.0,>=0.1.22->kagglehub[pandas-datasets]) (5.29.6)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas->kagglehub[pandas-datasets]) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->kagglehub[pandas-datasets]) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->kagglehub[pandas-datasets]) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->kagglehub[pandas-datasets]) (2026.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub[pandas-datasets]) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub[pandas-datasets]) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub[pandas-datasets]) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub[pandas-datasets]) (2026.6.17)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->kagglehub[pandas-datasets]) (1.17.0)

In [52]:
import numpy as np
import numpy.random as random
import scipy as sp
import pandas as pd
from pandas import Series,DataFrame
import os
import zipfile
import requests
import io

# Visualization Library
import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
%matplotlib inline

# Displayed to 3 decimal places
%precision 3

'%.3f'

some practice before titanic

In [53]:
my_series = Series([1,2,4,7,9])
print(my_series)

0    1
1    2
2    4
3    7
4    9
dtype: int64

In [54]:
my_series.index
my_series.values

array([1, 2, 4, 7, 9])

In [55]:
my_series2 = Series([10,20,30,50,80], index=['a', 'b', 'c', 'd', 'e'])
my_series2

a    10
b    20
c    30
d    50
e    80
dtype: int64

In [56]:
my_series2.index
my_series2.values

array([10, 20, 30, 50, 80])

In [57]:
my_data = {
    'name': ['ally', 'max', 'sam', 'robel', 'kaleabb'],
    'city': ['LA', 'addis ababa', 'seoul', 'bahirdar', 'milan'],
    'age': [23, 34, 21,29, 24]
}
my_df = DataFrame(my_data)
my_df

      name         city  age
0     ally           LA   23
1      max  addis ababa   34
2      sam        seoul   21
3    robel     bahirdar   29
4  kaleabb        milan   24

In [58]:
my_df.columns

Index(['name', 'city', 'age'], dtype='object')

In [59]:
# selcting columns
#my_df.age
my_df['age']

0    23
1    34
2    21
3    29
4    24
Name: age, dtype: int64

In [60]:
#multiple columns
my_df[['age','city']]

   age         city
0   23           LA
1   34  addis ababa
2   21        seoul
3   29     bahirdar
4   24        milan

In [61]:
#selcting specific row
my_df[0:3]

   name         city  age
0  ally           LA   23
1   max  addis ababa   34
2   sam        seoul   21

In [62]:
my_df[0:1]

   name city  age
0  ally   LA   23

In [63]:
#loc
my_df.loc[0]

name    ally
city      LA
age       23
Name: 0, dtype: object

In [64]:
my_df.loc[0:3]

    name         city  age
0   ally           LA   23
1    max  addis ababa   34
2    sam        seoul   21
3  robel     bahirdar   29

In [65]:
my_df.loc[0:3, ['name']]

    name
0   ally
1    max
2    sam
3  robel

In [66]:
my_df.loc[0:3, ['name','age']]

    name  age
0   ally   23
1    max   34
2    sam   21
3  robel   29

In [67]:
#iloc
my_df.iloc[0:3]

   name         city  age
0  ally           LA   23
1   max  addis ababa   34
2   sam        seoul   21

In [68]:
my_df.iloc[0:3, 0]

0    ally
1     max
2     sam
Name: name, dtype: object

In [69]:
my_df.iloc[0:3, 0:3]

   name         city  age
0  ally           LA   23
1   max  addis ababa   34
2   sam        seoul   21

In [70]:
my_df.iloc[0, 0]

'ally'

In [71]:
my_df.iloc[0:3, [1,2]]

          city  age
0           LA   23
1  addis ababa   34
2        seoul   21

In [72]:
my_df.iloc[0:3, 2]

0    23
1    34
2    21
Name: age, dtype: int64

In [73]:
my_df.at[1, 'name']

'max'

In [74]:
my_df.name

0       ally
1        max
2        sam
3      robel
4    kaleabb
Name: name, dtype: object

In [75]:
my_df['Gender'] = ['female','male', 'female', 'male', 'male']
my_df

      name         city  age  Gender
0     ally           LA   23  female
1      max  addis ababa   34    male
2      sam        seoul   21  female
3    robel     bahirdar   29    male
4  kaleabb        milan   24    male

In [77]:
my_df.at[2, 'age'] = 25
my_df

      name         city  age  Gender
0     ally           LA   23  female
1      max  addis ababa   34    male
2      sam        seoul   25  female
3    robel     bahirdar   29    male
4  kaleabb        milan   24    male

In [78]:
#extracting with condition
my_df['age'] >25

0    False
1     True
2    False
3     True
4    False
Name: age, dtype: bool

In [80]:
my_df[my_df['age'] >25]

    name         city  age Gender
1    max  addis ababa   34   male
3  robel     bahirdar   29   male

In [81]:
my_df[my_df['Gender'] == 'female']

   name   city  age  Gender
0  ally     LA   23  female
2   sam  seoul   25  female

In [83]:
my_df[(my_df['Gender'] == 'male') &(my_df['age'] > 23)]

      name         city  age Gender
1      max  addis ababa   34   male
3    robel     bahirdar   29   male
4  kaleabb        milan   24   male

In [84]:
my_df[(my_df['Gender'] =='female') | (my_df['age'] >25)]

    name         city  age  Gender
0   ally           LA   23  female
1    max  addis ababa   34    male
2    sam        seoul   25  female
3  robel     bahirdar   29    male

In [86]:
my_df[my_df['city'].isin(['LA', 'seoul'])]

   name   city  age  Gender
0  ally     LA   23  female
2   sam  seoul   25  female

In [87]:
my_df.isnull()

    name   city    age  Gender
0  False  False  False   False
1  False  False  False   False
2  False  False  False   False
3  False  False  False   False
4  False  False  False   False

In [89]:
my_df.isnull().sum()

name      0
city      0
age       0
Gender    0
dtype: int64

In [90]:
my_df.sort_index()

      name         city  age  Gender
0     ally           LA   23  female
1      max  addis ababa   34    male
2      sam        seoul   25  female
3    robel     bahirdar   29    male
4  kaleabb        milan   24    male

In [91]:
my_df.sort_values(by='age', ascending= True)

      name         city  age  Gender
0     ally           LA   23  female
4  kaleabb        milan   24    male
2      sam        seoul   25  female
3    robel     bahirdar   29    male
1      max  addis ababa   34    male

Using the Titanic dataset, do not modify any data. Your job is only to inspect and understand it.

Answer these questions:

How many rows and columns are there?

What are the column names?

What data type is each column?

Which columns have missing values? How many?

Which column has the most unique values?

What are the 5 most common values in Embarked (or another categorical column)?

What are the mean, min, and max of Age and Fare?

Which columns are numerical vs categorical?

Pick one random passenger and explain what each field means.
Write a 5-sentence summary describing the dataset as if you're introducing it to someone who's never seen it.

Rule: Don't clean, filter, or modify anything yet. Just explore and understand the data. The goal is to build the habit of inspecting a dataset before touching it.

In [4]:
# Install dependencies as needed:
# pip install kagglehub[pandas-datasets]
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the file you'd like to load
file_path = "Titanic-Dataset.csv"

# Load the latest version
df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "yasserh/titanic-dataset",
  file_path,
  # Provide any additional arguments like 
  # sql_query or pandas_kwargs. See the 
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

print("First 5 records:", df.head())

/tmp/ipykernel_3365/1732105544.py:10: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(

Using Colab cache for faster access to the 'titanic-dataset' dataset.
First 5 records:    PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0

   Parch            Ticket     Fare Cabin Embarked
0      0         A/5 21171   7.2500   NaN        S
1      0          PC 17599  71.2833   C85        C
2      0  STON/O2. 3101282   7.9250   NaN        S
3      0            113803  53.1000  C123        S
4      0            373450   8.0500   NaN        S

In [5]:
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C


| Column          | Description                                                                 |
| --------------- | --------------------------------------------------------------------------- |
| **PassengerId** | Unique ID assigned to each passenger.                                       |
| **Survived**    | Target variable: `0` = Did not survive, `1` = Survived.                     |
| **Pclass**      | Passenger class: `1` = First, `2` = Second, `3` = Third.                    |
| **Name**        | Full name of the passenger.                                                 |
| **Sex**         | Passenger's gender (`male` or `female`).                                    |
| **Age**         | Passenger's age in years.                                                   |
| **SibSp**       | Number of siblings/spouses aboard.                                          |
| **Parch**       | Number of parents/children aboard.                                          |
| **Ticket**      | Ticket number.                                                              |
| **Fare**        | Fare paid for the ticket.                                                   |
| **Cabin**       | Cabin number assigned to the passenger (many missing values).               |
| **Embarked**    | Port of embarkation: `C` = Cherbourg, `Q` = Queenstown, `S` = Southampton.  |

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [11]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [13]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

day 2

In [ ]:
#se3lecting data
df.Survived
df['Age']
df[['Parch', 'Fare']]

#replace- df,at[0, 'Survived'] = 1


df.isnull()
df.isnull().sum()

In [ ]:
#day 2 titanic

Explore the Titanic dataset:

Inspect the dataset

Select subsets with loc/iloc

Filter passengers (e.g., females in 1st class, age > 30)

Create a new feature (e.g., FamilySize = SibSp + Parch + 1)

Sort by Fare and Age

Count survival rates by gender using value_counts()

#select with i loc
df.loc[4]
df.loc[3:7]
df.loc[: , 'Age']
df.loc[:, ['PssengerId','Age']]

df.iloc[4]
df.iloc[0:4, [0,2]]

In [ ]:
#filter, females in 1st class, age > 30
df[(df['Sex']=='female') & (df['PClass']==1) & (df['Age'] >30)]

In [ ]:
#create a new feature, FAMILY SIZE = SIBSB + PARCH + 1
df['FamilySize'] = SibSp + Parch + 1
df.FamilySize

In [ ]:
#sort by fare and age
df.sort_values(by = 'fare', acending = False)
df.sort_values(by= 'age', ascending = False)

In [ ]:
#count survival rate by geneder
female_survival = np.sum(df[df(['Sex'] =='female') & (df['Survived']==1 )])
male_survival = np.sum(df[df(['Sex'] =='male') & (df['Survived']==1 )])

#learn value counts

In [ ]:
# Prepare data1
data1 = {
    'id': ['0', '1', '2', '3', '4', '6', '8', '11', '12', '13'],
    'city': ['Tokyo', 'Osaka', 'Kyoto', 'Hokkaido', 'Tokyo', 'Tokyo', 'Osaka', 'Kyoto', 'Hokkaido', 'Tokyo'],
    'birth_year': [1990, 1989, 1992, 1997, 1982, 1991, 1988, 1990, 1995, 1981],
    'name': ['Hiroshi', 'Akiko', 'Yuki', 'Satoru', 'Steeve', 'Mituru', 'Aoi', 'Tarou', 'Suguru', 'Mitsuo'],
    'tuition': [2999,4898, 8888, 2047, 7868, 9429, 3389]
}
df1 = DataFrame(data1)
df1

In [ ]:
data2 = {
    'id': ['14', '15', '16', '17', '18', '19', '20'],
    'city': ['addis ababa', 'bahirdar', 'hawassa', 'mekelle', 'harar', 'asossa', 'gondar'],
    'birth_year': [1990, 2001,1992, 1920, 1993,1932, 1988],
    'name': ['Alemu', 'tariku', 'kidist', 'helen', 'kaleabb', 'samrawit', 'Selam'],
    'grade':['A', 'A', 'B', 'B', 'C' , 'A', 'B' ],
    'major': ['biology', 'chemistry', 'biology', 'engineering', 'medicine', 'math', 'marketing']
    }
df2 = DataFrame(data2)
df2

In [ ]:
#inner join
pd.merge(df1, df2, on='id')

In [ ]:
pd.merge(df1, df2, left_on="id", right_on="city")

In [ ]:
#left ouer join
pd.merge(df1, df2 how='left')

In [ ]:
#full outer join
pd.merge(df1, df2 how='outer')

In [ ]:
#vertical join
pd.concat([df1,df2])

In [ ]:
#horizontal join
pd.concat([df1, df2], axis=1)